### PR TITLE
[Bug] Error saving contributions

### LINKED ISSUE #849: [Bug] Error saving contributions

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #849

image

### CODE REVIEW

File: app/controllers/account/benefits/plans/contributions/edit-all.js [hunk 1]
```diff
@@ -7,9 +7,9 @@ export default class ContributionsEditAllController extends Controller {
...
   @action
   async save (wp) {
-    let plans = await this.get(';model');
-    for (let i = 0; i <= plans.length; i++) {
-      await plans[i].set('wellnessPlan', wp);
+    let plans = await this.model;
+    for (let i = 0; i <= plans.length - 1; i++) {
+      plans[i].wellnessPlan = wp;
       await this.data.saveRecord(plans[i]);
     }
```
Comment (James1x0) [inline app/controllers/account/benefits/plans/contributions/edit-all.js:14]: https://github.com/associatedemployers/granite/blob/epic/%23554-benefits/app/services/data.js#L107-L111

**Review by James1x0 — CHANGES_REQUESTED** [review]
