### PR TITLE
[Fix] campaign setup notification drop downs

### LINKED ISSUE #477: [Bug] campaign notification drop downs in setup
not populating all company users, not saving additional emails

screen shot 2019-02-12 at 8 39 10 am

### PR DESCRIPTION
**Pull request by petersonbrock**
link created between company user and employee upon creation of company user will fill drop down.  additional email dropdown works as expected

closes #477

### CODE REVIEW

File: app/controllers/account/anatomy/company-users/new.js [hunk 1]
```diff
@@ -12,6 +12,15 @@ export default Controller.extend(addEdit, {
   }),
 
   actions: {
+    async save () {
+      let model = this.get('model');
+      let employee = await this.get('model.employee');
+      let user = await this.saveModel(model);
```
Comment (James1x0) [inline app/controllers/account/anatomy/company-users/new.js]: Can you combine these declarations?

Comment (petersonbrock) [reply app/controllers/account/anatomy/company-users/new.js]: yes
