### PR TITLE
[Bug] Blank screening question allowed

### LINKED ISSUE #631: [Bug] Blank screening question allowed
You are allowed to enter a blank screening question and it will show in quartz

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #631

### CODE REVIEW

File: app/mixins/controller-abstractions/add-edit.js [hunk 1]
```diff
@@ -16,13 +17,29 @@
...
+  getModelValidations (model) {
+    let validations = get(model, 'validations.messages'),
+        message = '';
+
+    if (!validations.length) {
+      return;
+    }
+
+    validations.map(x => {
+      message += `\n\u2022 ${x}`;
```
Comment (James1x0) [inline app/mixins/controller-abstractions/add-edit.js]: When we want to boil something down (validation messages) to something else (a single message), what should we use instead of map?

File: app/mixins/controller-abstractions/add-edit.js [hunk 2]
```diff
@@ -16,13 +17,29 @@
...
+import { map } from 'rsvp';
 import AjaxHooks from '../ajax-status';
 
 export default Mixin.create(AjaxHooks, {
+
   enableNotify:        true,
   transitionWithModel: true,
 
+  getModelValidations (model) {
+    let validations = get(model, 'validations.messages'),
```
Comment (James1x0) [inline app/mixins/controller-abstractions/add-edit.js]:
```suggestion
    const validations = get(model, 'validations.messages');
```

File: app/mixins/controller-abstractions/add-edit.js [hunk 3]
```diff
@@ -89,7 +113,9 @@ export default Mixin.create(AjaxHooks, {
 
       this._afterSave(record);
       return record;
-    }).catch(this.ajaxError.bind(this));
+    } catch (e) {
+      this.ajaxError.bind(this);
```
Comment (James1x0) [inline app/mixins/controller-abstractions/add-edit.js]: This doesn't show a message now.

File: app/models/validations/form-element.js [hunk 4]
```diff
@@ -0,0 +1,13 @@
+import { validator, buildValidations } from 'ember-cp-validations';
+
+export default buildValidations({
+
```
Comment (James1x0) [inline app/models/validations/form-element.js]: ✂️

File: app/mixins/controller-abstractions/add-edit.js [hunk 5]
```diff
@@ -16,13 +17,29 @@
  */
 import Mixin from '@ember/object/mixin';
 import { get } from '@ember/object';
-import { Promise, map } from 'rsvp';
+import { map } from 'rsvp';
 import AjaxHooks from '../ajax-status';
 
 export default Mixin.create(AjaxHooks, {
+
```
Comment (James1x0) [inline app/mixins/controller-abstractions/add-edit.js]: ✂️

File: app/mixins/controller-abstractions/add-edit.js (hunk 1 above)
Comment (JavaLavaMT) [reply app/mixins/controller-abstractions/add-edit.js]: dang, you got me. I even had a reduce function used but doubted myself

File: app/mixins/controller-abstractions/add-edit.js (hunk 3 above)
Comment (JavaLavaMT) [reply app/mixins/controller-abstractions/add-edit.js]: 🏁

File: app/controllers/account/job-opening/setup/screening.js [hunk 6]
```diff
@@ -34,26 +37,34 @@ export default Controller.extend(addEdit, {
...
-        f.destroyRecord();
-        this.set('model.screening', null);
-        this.get('target').send('saveAndContinue');
-        return;
+        try {
+          await f.destroyRecord();
+          this.set('model.screening', null);
+          await this.get('target').send('saveAndContinue');
+          this.ajaxSuccess();
+          return;
```
Comment (James1x0) [inline app/controllers/account/job-opening/setup/screening.js]: Move to outside try/catch

File: app/templates/components/form/form-element.hbs [hunk 7]
```diff
@@ -29,15 +29,15 @@
...
+        <label>*What would you like to ask for question #{{positionInForm}}?</label>
         {{input
           type="text"
           value=model.label
           placeholder=labelSuggestion}}
       </div>
 
       <div class="field">
-        <label>How should they answer?</label>
+        <label>*How should they answer?</label>
```
Comment (James1x0) [inline app/templates/components/form/form-element.hbs]:
```suggestion
        <label>How should they answer?*</label>
```

File: app/templates/components/form/form-element.hbs [hunk 8]
```diff
@@ -29,15 +29,15 @@
   {{#unless showingPreview}}
     <div class="two fields">
       <div class="field">
-        <label>What would you like to ask for question #{{positionInForm}}?</label>
+        <label>*What would you like to ask for question #{{positionInForm}}?</label>
```
Comment (James1x0) [inline app/templates/components/form/form-element.hbs]:
```suggestion
        <label>What would you like to ask for question #{{positionInForm}}?*</label>
```

File: app/controllers/account/job-opening/setup/screening.js (hunk 6 above)
Comment (James1x0) [inline app/controllers/account/job-opening/setup/screening.js]: Move outside the try/catch

File: app/controllers/account/job-opening/setup/screening.js [hunk 9]
```diff
@@ -1,8 +1,11 @@
 import Controller from '@ember/controller';
 import { computed } from '@ember/object';
 import addEdit from 'granite/mixins/controller-abstractions/add-edit';
+import ajaxStatus from 'granite/mixins/ajax-status';
+
+export default Controller.extend(addEdit, ajaxStatus, {
```
Comment (James1x0) [inline app/controllers/account/job-opening/setup/screening.js]: ajax status comes with addEdit?

File: app/mixins/controller-abstractions/add-edit.js [hunk 10]
```diff
@@ -70,17 +86,24 @@ export default Mixin.create(AjaxHooks, {
 
     let invalid = this._validateModel(_model);
 
+    let validationsError = this.get('enableModelValidations') ? await this.getModelValidations(_model) : false;
```
Comment (James1x0) [inline app/mixins/controller-abstractions/add-edit.js]:
```suggestion
    let validationsError = this.get('enableModelValidations') && await this.getModelValidations(_model);
```

File: app/mixins/controller-abstractions/add-edit.js [hunk 11]
```diff
@@ -89,7 +112,9 @@ export default Mixin.create(AjaxHooks, {
 
       this._afterSave(record);
       return record;
-    }).catch(this.ajaxError.bind(this));
+    } catch (e) {
+      throw e;
```
Comment (James1x0) [inline app/mixins/controller-abstractions/add-edit.js]: No longer calling ajaxError :( - outside handlers are now getting an exception instead of the error logged.

File: app/mixins/controller-abstractions/add-edit.js (hunk 10 above)
Comment (JavaLavaMT) [reply app/mixins/controller-abstractions/add-edit.js]: nice

File: app/mixins/controller-abstractions/add-edit.js [hunk 12]
```diff
@@ -16,13 +17,28 @@
...
+    const validations = get(model, 'validations.messages');
+
+    if (!validations.length) {
+      return;
+    }
+
+    let errorMessages = validations.reduce((message, x) => {
+      message.push(`\n\u2022 ${x}`);
+      return message;
+    }, []);
```
Comment (James1x0) [inline app/mixins/controller-abstractions/add-edit.js]:
```
let errorMessages = validations.map(message => `\n\u2022 ${x}`);
```

Accomplishes the same.
