### PR TITLE
[Bug] Employee page "more" sub-menu doesn't show on mobile

### LINKED ISSUE #743: [Bug] Employee page "more" sub-menu doesn't show on mobile

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #743 and #757 
menu

### CODE REVIEW

File: app/controllers/account/employee/index.js [hunk 1]
```diff
@@ -6,10 +6,38 @@ import { inject as service } from '@ember/service';
...
+      icon:  'history'
+    }, {
+      route: 'account.employee.index.counseling',
+      name:  'Counseling',
+      icon:  'folder open'
+    }, this.get('auth.user.company.exposeBetaModules') && {
+      route: 'account.employee.index.education',
+      name:  'Education & Training',
+      icon:  'graduation cap'
+    } ].filter(Boolean);
```
Comment (JavaLavaMT) [inline app/controllers/account/employee/index.js]: Nice!
