### PR TITLE
[Bug] ATS screening responses should show a humanized date if a date is used

### LINKED ISSUE #827: [Bug] ATS screening responses should show a humanized date if a date is used
in ats/open application

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #827

image

### CODE REVIEW

File: app/controllers/account/job-opening/campaign/job-application/index.js [hunk 1]
```diff
@@ -20,9 +20,20 @@ export default class JobApplicationController extends Controller {
...
+    groups.map(group => {
+      if (group.value && group.value.isArray()) {
+        group.date = moment(group.response.value.text).isValid()  ? moment(group.response.value.text).format('M/D/YYYY') : false;
+        return group;
+      }
+      group.date = moment(group.response.value).isValid() ? moment(group.response.value).format('M/D/YYYY') : false;
+      return group;
+    });
+
+    return groups;
```
Comment (James1x0) [inline app/controllers/account/job-opening/campaign/job-application/index.js:37]: There's a more succinct way to do this. Expand on the existing map function, don't iterate on steps twice.

File: app/templates/account/job-opening/campaign/job-application/index.hbs [hunk 2]
```diff
@@ -91,7 +91,11 @@
                 No response
               </div>
             {{/if}}
-            {{or group.response.value.text group.response.value}}
+            {{#if group.date}}
+              {{group.date}}
+            {{else}}
+              {{or group.response.value.text group.response.value}}
```
Comment (James1x0) [inline app/templates/account/job-opening/campaign/job-application/index.hbs:97]: Rather than pre-formatting, I'd rather you use a flag and use the time helper. This bring display config into the display markup. 👍

**Review by James1x0 — CHANGES_REQUESTED** [review]

File: app/controllers/account/job-opening/campaign/job-application/index.js [hunk 3]
```diff
@@ -20,9 +20,12 @@ export default class JobApplicationController extends Controller {
...
 
-    return steps && responses ? steps.toArray().map(step => ({
+    let groups = steps && responses ? steps.toArray().map(step => ({
       step,
-      response: responses.findBy('step', step.get('id'))
+      response: responses.findBy('step', step.get('id')),
+      date:     typeof responses.findBy('step', step.get('id')).value === 'array' ? moment(responses.findBy('step', step.get('id')).value.text).isValid() : moment(responses.findBy('step', step.get('id')).value).isValid()
     })) : false;
+
+    return groups;
```
Comment (James1x0) [inline app/controllers/account/job-opening/campaign/job-application/index.js:29]:
```suggestion
    return steps && responses ? steps.toArray().map(step => {
      let response = responses.findBy('step', step.get('id'));
      return {
        step,
        response,
        date: typeof response.value === 'array' ? moment(response.value.text).isValid() : moment(response.value).isValid()
    })) : false;
```

File: app/templates/account/job-opening/campaign/job-application/index.hbs [hunk 4]
```diff
@@ -91,7 +91,11 @@
                 No response
               </div>
             {{/if}}
-            {{or group.response.value.text group.response.value}}
+            {{#if group.date}}
+              {{or (time group.response.value) (time group.response.value.text)}}
```
Comment (James1x0) [inline app/templates/account/job-opening/campaign/job-application/index.hbs:95]:
```suggestion
              {{time (or group.response.value group.response.value.text)}}
```

File: app/controllers/account/job-opening/campaign/job-application/index.js (hunk 3 above)
Comment (JavaLavaMT) [reply app/controllers/account/job-opening/campaign/job-application/index.js:29]: yep way better way, not sure what I was thinking

File: app/controllers/account/job-opening/campaign/job-application/index.js [hunk 5]
```diff
@@ -22,7 +22,8 @@ export default class JobApplicationController extends Controller {
 
     return steps && responses ? steps.toArray().map(step => ({
       step,
-      response: responses.findBy('step', step.get('id'))
+      response: responses.findBy('step', step.get('id')),
+      date:     typeof this.response.value === 'array' ? moment(this.response.value.text).isValid() : moment(this.response.value).isValid()
```
Comment (James1x0) [inline app/controllers/account/job-opening/campaign/job-application/index.js:26]:
```suggestion
      date:     moment(typeof this.response.value === 'array' ? this.response.value.text : this.response.value).isValid()
```
