### PR TITLE
[Bug] auto w4 / i9 created date not showing

### LINKED ISSUE #910: [Bug] auto w4 / i9 created date not showing

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #910

image

### CODE REVIEW

File: app/components/list-item/employee-document-item.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ export default class ListItemEmployeeDocumentItemComponent extends Component {
   @computed.match('args.assignment.file.extension', /jpe?g|png|gif/i) imagePreview
 
   get file () {
-    return this.args.assignment.file;
+    return this.args.assignment.file.get('id') ? this.args.assignment.file : this.args.assignment.filledFile;
```
Comment (James1x0) [inline app/components/list-item/employee-document-item.js:14]:
```suggestion
    return this.args.assignment.belongsTo('file').id() ? this.args.assignment.file : this.args.assignment.filledFile;
```
