### PR TITLE
[Bug] Changes count flag is sticking

### LINKED ISSUE #642: [Bug] Changes count flag is sticking
the flag stays there until refreshed

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #642

### CODE REVIEW

File: app/routes/account/employees/changes.js [hunk 1]
```diff
@@ -1,13 +1,18 @@
...
 
   model () {
     return this.get('store').query('change', {
       reviewedOn: { $not: { $type: 9 } },
       sort:       { created: -1 }
     });
+  },
+
+  actions: {
+    willTransition () {
```
Comment (James1x0) [inline app/routes/account/employees/changes.js]: Whenever we transition away from this page, we cause a refresh. This is no good. Think about if we are on this page, click to navigate into settings, we'll pointlessly cause a refresh of the employees model hook.

File: app/routes/account/employees/changes.js [hunk 2]
```diff
@@ -1,13 +1,20 @@
...
 
   model () {
     return this.get('store').query('change', {
       reviewedOn: { $not: { $type: 9 } },
       sort:       { created: -1 }
     });
+  },
+
+  actions: {
+    willTransition (transition) {
```
Comment (James1x0) [inline app/routes/account/employees/changes.js]: I still don't like the use of willTransition...

We already have a refresh call here: https://github.com/associatedemployers/granite/blob/master/app/controllers/account/employees/changes.js#L19

So why not implement "refresh" as an action here, return `true` to cause the action to bubble to  `app/routes/account/employees.js`'s refresh action.

Comment (JavaLavaMT) [reply app/routes/account/employees/changes.js]: I changed it and it just worked. I don't fully understand as to how it works
