### PR TITLE
Dropzone not working

### LINKED ISSUE #390: [Bug] Dropzone not working
Error: No Dropzone found for given element. This is probably because you're trying to access it before Dropzone had the time to initialize. Use the `init` option to setup any additional observers on your Dropzone.

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #390

### CODE REVIEW

File: app/components/modals/ats-add-applicant.js [hunk 1]
```diff
@@ -5,10 +5,14 @@ import { inject as service } from '@ember/service';
...
 import $ from 'jquery';
 
+
 export default Component.extend(ajaxStatus, {
   store:                   service(),
   applicantRequiredFields: [ 'firstName', 'lastName', 'phone', 'email' ],
   fileIsAdded:             false,
+  test:                    false,
+
+
```
Comment (James1x0) [inline app/components/modals/ats-add-applicant.js]: What's all this cruft in here? Please clean up
