### PR TITLE
[Fix] Refresh change count after resolving change

### LINKED ISSUE #790: [Bug] Changes count didnt refresh
after confirming a change, transitions to employees page and the change count on the tab is still the same

### PR DESCRIPTION
**Pull request by petersonbrock**
closes #790

### CODE REVIEW

File: app/routes/account/employees.js [hunk 1]
```diff
@@ -14,4 +15,10 @@ export default class AccountEmployeesRoute extends Route {
 
     return { changeQueue: response && response.count };
   }
+
+  @action
+  refresher () {
+    //gets used from change route to refresh change count
```
Comment (James1x0) [inline app/routes/account/employees.js:21]: 👏
